use pikacardDB
DROP TABLE IF EXISTS topics;
CREATE TABLE "topics" (
	"id"	INTEGER,
	"topic_name"	TEXT,
	"created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
)
DROP TABLE IF EXISTS cards;
CREATE TABLE "cards" (
	"id"	INTEGER,
	"topic_id"	TEXT NOT NULL,
	"front"	TEXT,
	"back"	TEXT,
	"known"	INTEGER NOT NULL DEFAULT 0,
	"created"	TEXT DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY("topic_id") REFERENCES "topics"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);